# Generated by Django 5.1.4 on 2025-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointapp', '0003_remove_user_avatar_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
