# Generated by Django 5.1.4 on 2025-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointapp', '0004_alter_criteria_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('name', 'semester')},
        ),
    ]
