# Generated by Django 5.1.4 on 2025-01-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointapp', '0005_alter_criteria_name_alter_criteria_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'academic_year')},
        ),
    ]
