# Generated by Django 5.1.4 on 2025-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointapp', '0008_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetailextractactivity',
            name='evidence',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
